### PR TITLE
DHIS2-8163: Handle different scheduling types

### PR DESCRIPTION
**Pull request by Mohammer5**
Fixes DHIS2-8163

* A mapping between job types and scheduling types is now stored
* Said mapping is used to show different edit/add form inputs depending on the scheduling type
* The list overview shows the delay between runs instead of next execution time

### CODE REVIEW

**Comment by varl** [comment]
Good work ! :thumbsup:

I found a few things when testing. Will add in separate comments so they can be resolved individually.

**Comment by varl** [comment]
I noticed that when I added additional parameters in the "New job", they either aren't saved, or aren't shown when editing the job:

New job:

2020-01-30-091101_1066x739_scrot

Edit job:

2020-01-30-091115_1045x885_scrot

**Comment by varl** [comment]
This might be a consequence of how it works behind the scenes but I found it confusing:

If I start the job, it says that it is "RUNNING":

2020-01-30-091302_1066x220_scrot

If I click on the job for the detail page, it says that the job ran and the job failed:

2020-01-30-091313_1050x148_scrot

And if I go back to the main list it still says RUNNING:

2020-01-30-091333_1059x210_scrot

Now, the failure itself is rather cryptic on the backend, but there's no indication if it's a server error or a client side error. I seeded the database with the latest dev db-dump and running the latest development image, so I assume that this feature is working:

```
 core_1     | Caused by: java.util.concurrent.ExecutionException: org.springframework.jdbc.BadSqlGrammarException: StatementCallback; $ad SQL grammar [insert into analytics_event_temp_vbqh0ynb2wv_0 ("uidlevel1","uidlevel2","uidlevel3","uidlevel4","uIuxlbV1vRT","Cbuj0VC$DjL","Bpx0589u8y0","J5jldMd8OHv","C31vHZqu0qU","SooXFOUnciJ","daily","weekly","weeklywednesday","weeklythursday","weeklysaturday","wee$lysunday","biweekly","monthly","bimonthly","quarterly","sixmonthly","sixmonthlyapril","sixmonthlynov","yearly","financialapril","finan$ialjuly","financialoct","financialnov","qrur9Dvnyt5","F3ogKBuviRA","oZg33kd9taw","qrur9Dvnyt5_Yf6UHoPkdS6","qrur9Dvnyt5_TiOkbpGEud4","psi","pi","ps","ao","enrollmentdate","incidentdate","executiondate","duedate","completeddate","created","lastupdated","pistatus","psista
tus","psigeometry","longitude","latitude","ou","ouname","oucode") select ous."uidlevel1",ous."uidlevel2",ous."uidlevel3",ous."uidlevel4
",ougs."uIuxlbV1vRT",ougs."Cbuj0VCyDjL",ougs."Bpx0589u8y0",ougs."J5jldMd8OHv",acs."C31vHZqu0qU",acs."SooXFOUnciJ",dps."daily",dps."week
ly",dps."weeklywednesday",dps."weeklythursday",dps."weeklysaturday",dps."weeklysunday",dps."biweekly",dps."monthly",dps."bimonthly",dps
."quarterly",dps."sixmonthly",dps."sixmonthlyapril",dps."sixmonthlynov",dps."yearly",dps."financialapril",dps."financialjuly",dps."fina
ncialoct",dps."financialnov",(select cast(eventdatavalues #>> '{qrur9Dvnyt5, value}' as bigint) from programstageinstance where program
stageinstanceid=psi.programstageinstanceid  and eventdatavalues #>> '{qrur9Dvnyt5,value}' ~* '^(-?[0-9]+)(\.[0-9]+)?$') as "qrur9Dvnyt5
",(select ST_GeomFromGeoJSON('{"type":"Point", "coordinates":' || (eventdatavalues #>> '{F3ogKBuviRA, value}') || ', "crs":{"type":"nam
e", "properties":{"name":"EPSG:4326"}}}') from programstageinstance where programstageinstanceid=psi.programstageinstanceid ) as "F3ogK
BuviRA",(select eventdatavalues #>> '{oZg33kd9taw, value}' from programstageinstance where programstageinstanceid=psi.programstageinsta
nceid ) as "oZg33kd9taw",(select l.uid from maplegend l inner join programstageinstance on l.startvalue <= cast(eventdatavalues #>> '{q
rur9Dvnyt5, value}' as bigint) and l.endvalue > cast(eventdatavalues #>> '{qrur9Dvnyt5, value}' as bigint) and l.maplegendsetid=240433
and programstageinstanceid=psi.programstageinstanceid  and eventdatavalues #>> '{qrur9Dvnyt5,value}' ~* '^(-?[0-9]+)(\.[0-9]+)?$') as "
qrur9Dvnyt5_Yf6UHoPkdS6",(select l.uid from maplegend l inner join programstageinstance on l.startvalue <= cast(eventdatavalues #>> '{q
rur9Dvnyt5, value}' as bigint) and l.endvalue > cast(eventdatavalues #>> '{qrur9Dvnyt5, value}' as bigint) and l.maplegendsetid=906836
and programstageinstanceid=psi.programstageinstanceid  and eventdatavalues #>> '{qrur9Dvnyt5,value}' ~* '^(-?[0-9]+)(\.[0-9]+)?$') as "
qrur9Dvnyt5_TiOkbpGEud4",psi.uid,pi.uid,ps.uid,ao.uid,pi.enrollmentdate,pi.incidentdate,psi.executiondate,psi.duedate,psi.completeddate
,psi.created,psi.lastupdated,pi.status,psi.status,psi.geometry,CASE WHEN 'POINT' = GeometryType(psi.geometry) THEN ST_X(psi.geometry) E
LSE null END,CASE WHEN 'POINT' = GeometryType(psi.geometry) THEN ST_Y(psi.geometry) ELSE null END,ou.uid,ou.name,ou.code from programst
ageinstance psi inner join programinstance pi on psi.programinstanceid=pi.programinstanceid inner join programstage ps on psi.programst
ageid=ps.programstageid inner join program pr on pi.programid=pr.programid and pi.deleted is false inner join categoryoptioncombo ao on
 psi.attributeoptioncomboid=ao.categoryoptioncomboid left join trackedentityinstance tei on pi.trackedentityinstanceid=tei.trackedentit
yinstanceid and tei.deleted is false inner join organisationunit ou on psi.organisationunitid=ou.organisationunitid left join _orgunits
tructure ous on psi.organisationunitid=ous.organisationunitid left join _organisationunitgroupsetstructure ougs on psi.organisationunit
id=ougs.organisationunitid and (cast(date_trunc('month', psi.executiondate) as date)=ougs.startdate or ougs.startdate is null) inner jo
in _categorystructure acs on psi.attributeoptioncomboid=acs.categoryoptioncomboid left join _dateperiodstructure dps on cast(psi.execut
iondate as date)=dps.dateperiod where psi.lastupdated < '2020-01-30T08:15:47' and psi.lastupdated >= '2019-08-21T11:00:29' and pr.progr
amid=424482 and psi.organisationunitid is not null and psi.executiondate is not null and psi.deleted is false ]; nested exception is or
g.postgresql.util.PSQLException: ERROR: relation "_orgunitstructure" does not exist
 core_1     |   Position: 3621
core_1     |    at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_232]
 core_1     |   at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_232]
 core_1     |   at org.hisp.dhis.commons.util.ConcurrentUtils.waitForCompletion(ConcurrentUtils.java:59) ~[dhis-support-commons-2.34-SN
APSHOT.jar:?]
 core_1     |   ... 15 more
```

**Comment by Mohammer5** [comment]
> I noticed that when I added additional parameters in the "New job", they either aren't saved, or aren't shown when editing the job:

@varl good catch, I simply didn't show them, they were there, was a quick'n'easy fix. Done

**Pull request merged**
